version: '3.9'

services:
  database:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTRGES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"